// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMb0M9SL6cnoaC2lVMjH2sb-z0Xtm9EWo',
    appId: '1:350748893934:web:0152c71b96485a9ad009ff',
    messagingSenderId: '350748893934',
    projectId: 'immopro-8a8e8',
    authDomain: 'immopro-8a8e8.firebaseapp.com',
    storageBucket: 'immopro-8a8e8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQHYde0Vv_oNi78ocMv7NrcyD9RQabVXY',
    appId: '1:350748893934:ios:eb5beb1453c604e4d009ff',
    messagingSenderId: '350748893934',
    projectId: 'immopro-8a8e8',
    storageBucket: 'immopro-8a8e8.firebasestorage.app',
    iosBundleId: 'com.example.immoproMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMb0M9SL6cnoaC2lVMjH2sb-z0Xtm9EWo',
    appId: '1:350748893934:web:a170b9748a6e53add009ff',
    messagingSenderId: '350748893934',
    projectId: 'immopro-8a8e8',
    authDomain: 'immopro-8a8e8.firebaseapp.com',
    storageBucket: 'immopro-8a8e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQHYde0Vv_oNi78ocMv7NrcyD9RQabVXY',
    appId: '1:350748893934:ios:eb5beb1453c604e4d009ff',
    messagingSenderId: '350748893934',
    projectId: 'immopro-8a8e8',
    storageBucket: 'immopro-8a8e8.firebasestorage.app',
    iosBundleId: 'com.example.immoproMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXoDckfEDTsljbnUDulOmWNPa4f7eqS0g',
    appId: '1:350748893934:android:4e8f8bafc1e0d535d009ff',
    messagingSenderId: '350748893934',
    projectId: 'immopro-8a8e8',
    storageBucket: 'immopro-8a8e8.firebasestorage.app',
  );
}
